services:
  # Service pour l'application Laravel
#  app:
#    image: php:8.0-fpm
#    container_name: laravel_app
#    working_dir: /var/www
#    volumes:
#      - ./:/var/www
#      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
#    networks:
#      - laravel
#
#  # Service pour le serveur web Nginx
#  web:
#    image: nginx:alpine
#    container_name: laravel_web
#    depends_on:
#      - app
#    ports:
#      - "8000:80"
#    volumes:
#      - ./:/var/www
#      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - laravel

  # Service pour la base de données MySQL
  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artisan_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3300:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
