name: Build Docker Container and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout du repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuration de QEMU pour la compatibilité multi-architecture
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configuration de Docker Buildx pour les builds avancés
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.ACCES_TOKEN }}

      # Build et push de l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: carolefm/back:latest

      # Configuration de l'agent SSH
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Ajouter le serveur aux hôtes connus
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 212.47.240.186 >> ~/.ssh/known_hosts

      # Copier le fichier Docker Compose vers le serveur
      - name: Copy Docker Compose file to server
        run: |
          scp -rp docker-compose.yml campus@212.47.240.186:/path/to/deployment

      # Déployer l'application
      - name: Deploy to server
        run: |
          ssh campus@212.47.240.186 << 'EOF'
            cd /path/to/deployment
            docker-compose down
            docker-compose pull
            docker-compose up -d
            exit
          EOF

